### ISSUE TITLE
LTC new syntax proposal (RFC)

### ISSUE THREAD

**Issue by UARTman** [laterem/ltc#9]
# Syntax proposal
## Variables
```
a = 10
b = -2.5
c = ’Hello world!’
d = ”Hello world!”
e = SomeFunction()
foo = b
bar = OtherFunction(a, b)
```
## Comments
```
foo = baz   #Комментарий
# Комментарий на всю строку
```
## Rendring to HTML
You can use user-defined variables in the HTML templates.

HTML file:
```html
<p>
    The dolphins say it's {{ a }}.
</p>
```

LTC file:
```
a = 42
```
## Using form data
You can use data returned by the student like this:

HTML file:
```html
<input name=”answer” type=”text”>
```

LTC file:
```
a = $answer 
b = SomeFunction($answer)
``` 
## Checking answers
You can check the returned answers using `check` statements. The value you give to `check` should be a boolean.

HTML file:
```html
<input name=”answer” type=”text”>
```
LTC file:
```
check Equals($answer, 42)
# Or
x = SomeFunction($answer)
check Equals(x, 42)
```
## Parameters
You allow the users of the template to change some variables by using `export` keyword.

LTC file:
```
export title = ’Hello math students!’ 

desc = ’Good luck with math!’
export desc 
```
## Constraints
If your template uses randomly generated data, you can ensure that it matches certain conditions. To do this, use the keyword `constrain` and pass it a boolean expression. The generator will supply random values until all `constrain` statements are true (or until it reaches 100, at which point it will return an error).

LTC file:
```
foobar = SomeRandomFunction()

constrain NotEqual(foobar, 42)
```

**Comment by spidzsaus** [comment]
Proposal approved, most of the proposed syntax changes are soon to be implemented. Thank you for contributing to the Laterem project!
